### ISSUE TITLE
make code structured, fast and efficient

### ISSUE THREAD

**Issue by nsvaidya** [nsvaidya/strcmp#1]
This program extracts out the same lines from more than one files, which are having string dump of malware samples. The code is working, but it is unstructured, slow and inefficient. Any help will be appreciated.

**Comment by HoussemCharf** [comment]
Hi i'd like to help in this :)

**Comment by nsvaidya** [comment]
Sure, @HoussemCharf , your contribution will be appreciated.

**Comment by sravanbrahma** [comment]
Can you also put the file which you are trying to analyse? It would be more helpful and quicker to replicate and evaluate performance.

**Comment by nsvaidya** [comment]
You can now find the sample files in repository.

**Comment by sravanbrahma** [comment]
Now are you happy with performance after recent pull request  merge with hashset ?

**Comment by nsvaidya** [comment]
Yes. Thanks to all of you.
